# reporter/html_reporter.py
import os
from datetime import datetime
from typing import List, Dict, Any
from jinja2 import Template
from models import Finding

# HTML template using inline styles (self-contained) with download button
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>EMailGuard Report - {{ metadata.subject }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.4; }
        .container { max-width: 1200px; margin: auto; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 5px; }
        .risk-badge { display: inline-block; padding: 5px 10px; border-radius: 4px; font-weight: bold; }
        .risk-Safe { background-color: #2ecc71; color: white; }
        .risk-Moderate { background-color: #f39c12; color: white; }
        .risk-High { background-color: #e67e22; color: white; }
        .risk-Critical { background-color: #e74c3c; color: white; }
        .score-box { font-size: 18px; margin: 10px 0; display: flex; align-items: center; gap: 15px; flex-wrap: wrap; }
        .download-btn { background-color: #3498db; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-size: 14px; text-decoration: none; display: inline-block; }
        .download-btn:hover { background-color: #2980b9; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
        th { background-color: #f2f2f2; }
        .snippet { background-color: #f8f8f8; font-family: monospace; white-space: pre-wrap; word-break: break-all; max-height: 150px; overflow: auto; }
        .correlation-item { background-color: #e8f4f8; padding: 8px; margin: 5px 0; border-left: 4px solid #3498db; }
        footer { margin-top: 30px; font-size: 12px; color: #7f8c8d; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
    <script>
        function downloadReport() {
            // Get the entire HTML content of the current page
            const htmlContent = document.documentElement.outerHTML;
            const blob = new Blob([htmlContent], {type: 'text/html'});
            const a = document.createElement('a');
            const url = URL.createObjectURL(blob);
            a.href = url;
            a.download = 'emailguard_report_{{ metadata.subject[:30] }}.html';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }
    </script>
</head>
<body>
<div class="container">
    <h1>EMailGuard - CSS Fingerprinting Analysis Report</h1>

    <h2>Email Metadata</h2>
    <ul>
        <li><strong>Subject:</strong> {{ metadata.subject }}</li>
        <li><strong>From:</strong> {{ metadata.from }}</li>
        <li><strong>Date:</strong> {{ metadata.date }}</li>
    </ul>

    <h2>Risk Assessment</h2>
    <div class="score-box">
        <span class="risk-badge risk-{{ risk.label }}">{{ risk.label }}</span>
        Score: {{ risk.score }}/100
        (Base: {{ risk.base_total }} + Boosts: {{ risk.boost_total }})
        <button class="download-btn" onclick="downloadReport()">📥 Download HTML Report</button>
    </div>

    <h2>Correlation Insights</h2>
    {% if correlation_insights %}
        {% for ins in correlation_insights %}
        <div class="correlation-item">
            <strong>{{ ins.description }}</strong> (Boost: +{{ ins.boost }})
        </div>
        {% endfor %}
    {% else %}
        <p>No correlation patterns detected.</p>
    {% endif %}

    <h2>Detected Fingerprinting Techniques ({{ findings|length }})</h2>
    <table>
        <thead>
            <tr><th>Technique</th><th>Risk</th><th>Paper Section</th><th>Matched Snippet</th><th>Description</th><th>Mitigation</th></tr>
        </thead>
        <tbody>
        {% for f in findings %}
        <tr>
            <td>{{ f.technique }}</td>
            <td>{{ f.risk_level }}</td>
            <td>{{ f.paper_section }}</td>
            <td class="snippet">{{ f.snippet[:300] }}{% if f.snippet|length > 300 %}...{% endif %}</td>
            <td>{{ f.description }}</td>
            <td>{{ f.mitigation }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <footer>
        Generated by EMailGuard on {{ timestamp }}<br>
        Based on "Cascading Spy Sheets" (NDSS 2025) – static CSS fingerprinting detection.
    </footer>
</div>
</body>
</html>
"""

def generate_html_report(findings: List[Finding],
                         metadata: Dict[str, str],
                         risk: Dict[str, Any],
                         correlation_insights: List[Dict[str, Any]],
                         output_path: str) -> None:
    """Generate a self-contained HTML report."""
    template = Template(HTML_TEMPLATE)
    html_output = template.render(
        findings=findings,
        metadata=metadata,
        risk=risk,
        correlation_insights=correlation_insights,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_output)